---

- name: Create Marathon conf directory
  file: path=/etc/marathon/conf state=directory

- name: Create Marathon plugins directory
  file: path=/etc/marathon/plugins state=directory

- name: Copy Sensetif Auth plugin
  copy: src=sensetif-auth.jar dest="/etc/marathon/plugins/sensetif-auth.jar" mode=755

- name: Copy Marathon plugins.conf
  template: src=plugins.conf dest="/etc/marathon/plugins.conf" mode=755

- name: Create Marathon security directory
  file: path=/etc/marathon/security state=directory mode=700

- name: Set required --master option
  template: src=master.j2 dest=/etc/marathon/conf/master

- name: Remove optional --artifact_store option
  file: path=/etc/marathon/conf/artifact_store state=absent
  when: artifact_store == ""

- name: Set optional --artifact_store option
  template: src=artifact_store.j2 dest=/etc/marathon/conf/artifact_store
  when: artifact_store != ""

- name: Remove optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=absent
  when: checkpoint == ""

- name: Set optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=touch
  when: checkpoint != ""

- name: Remove optional --zk option
  file: path=/etc/marathon/conf/zk state=absent
  when: marathon_zookeeper_state == ""

- name: Set optional --zk option
  template: src=zk.j2 dest=/etc/marathon/conf/zk
  when: marathon_zookeeper_state != ""

- name: Set --hostname option
  template: src=hostname.j2 dest=/etc/marathon/conf/hostname

- name: Set --http-port option
  template: src=http_port.j2 dest=/etc/marathon/conf/http_port

- name: Set --plugin_dir option
  template: src=plugin_dir.j2 dest=/etc/marathon/conf/plugin_dir

- name: Set --plugin_conf option
  template: src=plugin_conf.j2 dest=/etc/marathon/conf/plugin_conf

- name: Set --mesos_role  option
  template: src=mesos_role.j2 dest=/etc/marathon/conf/mesos_role

- name: Set --mesos_authentication_principal option
  template: src=mesos_authentication_principal.j2 dest=/etc/marathon/conf/mesos_authentication_principal

- name: Set --mesos_authentication_secret_file option
  template: src=mesos_authentication_secret_file.j2 dest=/etc/marathon/conf/mesos_authentication_secret_file

- name: Setup secret file
  template: src=marathon_secret.j2 dest=/etc/marathon/security/marathon_secret mode=600

- name: Setup rsyslog conf file
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.d/marathon.conf

- name: Upstart check
  stat: path=/etc/init/
  register: etc_init_check

- name: systemd check
  stat: path=/usr/lib/systemd/system/
  register: systemd_check
  
- name: Upstart environment variables 
  lineinfile: dest=/etc/init/marathon.conf backup=yes state=present insertbefore='exec.*' line="env {{ item }}"
  with_items: "{{marathon_env_vars}}"
  when: etc_init_check.stat.exists == true
  
- name: systemd environment variables
  template: src=sysconfig.j2 dest=/etc/sysconfig/marathon 
  when: systemd_check.stat.exists == true

