---

- name: Create Marathon conf directory
  file: path=/etc/marathon/conf state=directory

- name: Create Marathon plugins directory
  file: path=/etc/marathon/plugins state=directory

- name: Copy Sensetif Auth plugin
  copy: src=sensetif-auth.jar dest="/etc/marathon/plugins/sensetif-auth.jar" mode=755

- name: Copy Marathon plugins.conf
  template: src=plugins.conf.j2 dest="/etc/marathon/plugins.conf" mode=755

- name: Create Marathon security directory
  file: path=/etc/marathon/security state=directory mode=700

- name: Remove optional --artifact_store option
  file: path=/etc/marathon/conf/artifact_store state=absent
  when: artifact_store == ""

- name: Set optional --artifact_store option
  template: src=artifact_store.j2 dest=/etc/marathon/conf/artifact_store
  when: artifact_store != ""

- name: Remove optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=absent
  when: checkpoint == ""

- name: Set optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=touch
  when: checkpoint != ""
  notify: restart marathon

- name: Remove optional --zk option
  file: path=/etc/marathon/conf/zk state=absent
  when: marathon_zookeeper_state == ""

- name: Set optional --zk option
  template: src=zk.j2 dest=/etc/marathon/conf/zk
  when: marathon_zookeeper_state != ""
  notify: restart marathon

- name: Set --hostname option
  template: src=hostname.j2 dest=/etc/marathon/conf/hostname
  notify: restart marathon

- name: Set required --master option
  template: src=master.j2 dest=/etc/marathon/conf/master
  notify: restart marathon

- name: Set --http-port option
  template: src=http_port.j2 dest=/etc/marathon/conf/http_port
  notify: restart marathon

- name: Set --http-credentials option
  template: src=http_credentials.j2 dest=/etc/marathon/conf/http_credentials
  notify: restart marathon

# I have problem enable https proxying.
#- name: Set --ssl_keystore_path option
#  template: src=ssl_keystore_path.j2 dest=/etc/marathon/conf/ssl_keystore_path
#  notify: restart marathon
#
#- name: Set --ssl_keystore_password option
#  template: src=ssl_keystore_password.j2 dest=/etc/marathon/conf/ssl_keystore_password
#  notify: restart marathon

- name: Set --framework_name option
  template: src=framework_name.j2 dest=/etc/marathon/conf/framework_name
  notify: restart marathon

#- name: Set --plugin_dir option
#  template: src=plugin_dir.j2 dest=/etc/marathon/conf/plugin_dir
#
#- name: Set --plugin_conf option
#  template: src=plugin_conf.j2 dest=/etc/marathon/conf/plugin_conf
#

- name: Remove --plugin_dir option
  file: path=/etc/marathon/conf/plugin_dir state=absent
  notify: restart marathon

- name: Remove --plugin_conf option
  file: path=/etc/marathon/conf/plugin_conf state=absent
  notify: restart marathon

- name: Set --mesos_role  option
  template: src=mesos_role.j2 dest=/etc/marathon/conf/mesos_role
  notify: restart marathon

- name: Set --mesos_authentication_principal option
  template: src=mesos_authentication_principal.j2 dest=/etc/marathon/conf/mesos_authentication_principal
  notify: restart marathon

- name: Set --mesos_authentication_secret_file option
  template: src=mesos_authentication_secret_file.j2 dest=/etc/marathon/conf/mesos_authentication_secret_file
  notify: restart marathon

- name: Setup secret file
  template: src=marathon_secret.j2 dest=/etc/marathon/security/marathon_secret mode=600
  notify: restart marathon

- name: Setup rsyslog conf file
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.d/marathon.conf
  notify: restart rsyslog

- name: systemd environment variables
  template: src=sysconfig.j2 dest=/etc/sysconfig/marathon 
  notify: restart marathon

