---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Add mesosphere repo
  yum: pkg={{ mesosphere_yum_repo }} state=present

- name: Install Marathon
  yum: pkg={{ marathon_yum_package }} state=present

- include: conf.yml

